/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package project;

/**
 *
 * @author acidb
 */
public class Step3 extends javax.swing.JFrame {

    /**
     * Creates new form ch3
     */
    public Step3() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        buttonGroup2 = new javax.swing.ButtonGroup();
        buttonGroup3 = new javax.swing.ButtonGroup();
        buttonGroup4 = new javax.swing.ButtonGroup();
        buttonGroup5 = new javax.swing.ButtonGroup();
        buttonGroup6 = new javax.swing.ButtonGroup();
        buttonGroup7 = new javax.swing.ButtonGroup();
        buttonGroup8 = new javax.swing.ButtonGroup();
        buttonGroup9 = new javax.swing.ButtonGroup();
        buttonGroup10 = new javax.swing.ButtonGroup();
        buttonGroup11 = new javax.swing.ButtonGroup();
        jPanel1 = new javax.swing.JPanel();
        closeButton = new javax.swing.JButton();
        previousButton = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        step3Ref1tp = new javax.swing.JTabbedPane();
        jPanel3 = new javax.swing.JPanel();
        step3Ref1Q1TP = new javax.swing.JTabbedPane();
        jPanel4 = new javax.swing.JPanel();
        jScrollPane2 = new javax.swing.JScrollPane();
        step3Ref1Q1TA = new javax.swing.JTextArea();
        jPanel7 = new javax.swing.JPanel();
        step3Ref1Q1rbYes = new javax.swing.JRadioButton();
        step3Ref1Q1rbNo = new javax.swing.JRadioButton();
        step3Ref1Q1rbNA = new javax.swing.JRadioButton();
        step3Ref1Q1rbObs = new javax.swing.JRadioButton();
        jPanel6 = new javax.swing.JPanel();
        jScrollPane3 = new javax.swing.JScrollPane();
        step3Ref1Q1NotesTA = new javax.swing.JTextArea();
        jPanel5 = new javax.swing.JPanel();
        step3Ref1Q2TP = new javax.swing.JTabbedPane();
        jPanel8 = new javax.swing.JPanel();
        jScrollPane4 = new javax.swing.JScrollPane();
        step3Ref2Q1TA = new javax.swing.JTextArea();
        jPanel9 = new javax.swing.JPanel();
        step3Ref2Q1rbYes = new javax.swing.JRadioButton();
        step3Ref2Q1rbNo = new javax.swing.JRadioButton();
        step3Ref2Q1rbNA = new javax.swing.JRadioButton();
        step3Ref2Q1rbObs = new javax.swing.JRadioButton();
        jPanel10 = new javax.swing.JPanel();
        jScrollPane5 = new javax.swing.JScrollPane();
        step3Ref2Q1NotesTA = new javax.swing.JTextArea();
        jPanel11 = new javax.swing.JPanel();
        step3Ref1Q3TP = new javax.swing.JTabbedPane();
        jPanel37 = new javax.swing.JPanel();
        jScrollPane8 = new javax.swing.JScrollPane();
        step3Ref3Q1TA = new javax.swing.JTextArea();
        jPanel38 = new javax.swing.JPanel();
        step3Ref3Q1rbYes = new javax.swing.JRadioButton();
        step3Ref3Q1rbNo = new javax.swing.JRadioButton();
        step3Ref3Q1rbNA = new javax.swing.JRadioButton();
        step3Ref3Q1rbObs = new javax.swing.JRadioButton();
        jPanel39 = new javax.swing.JPanel();
        jScrollPane9 = new javax.swing.JScrollPane();
        step3Ref3Q1NotesTA = new javax.swing.JTextArea();
        jPanel12 = new javax.swing.JPanel();
        step3Ref1Q4TP = new javax.swing.JTabbedPane();
        jPanel40 = new javax.swing.JPanel();
        jScrollPane10 = new javax.swing.JScrollPane();
        step3Ref4Q1TA = new javax.swing.JTextArea();
        jPanel41 = new javax.swing.JPanel();
        step3Ref4Q1rbYes = new javax.swing.JRadioButton();
        step3Ref4Q1rbNo = new javax.swing.JRadioButton();
        step3Ref4Q1rbNA = new javax.swing.JRadioButton();
        step3Ref4Q1rbObs = new javax.swing.JRadioButton();
        jPanel42 = new javax.swing.JPanel();
        jScrollPane11 = new javax.swing.JScrollPane();
        step3Ref4Q1NotesTA = new javax.swing.JTextArea();
        jPanel13 = new javax.swing.JPanel();
        step3Ref1Q5TP = new javax.swing.JTabbedPane();
        jPanel43 = new javax.swing.JPanel();
        jScrollPane12 = new javax.swing.JScrollPane();
        step3Ref5Q1TA = new javax.swing.JTextArea();
        jPanel44 = new javax.swing.JPanel();
        step3Ref5Q1rbYes = new javax.swing.JRadioButton();
        step3Ref5Q1rbNo = new javax.swing.JRadioButton();
        step3Ref5Q1rbNA = new javax.swing.JRadioButton();
        step3Ref5Q1rbObs = new javax.swing.JRadioButton();
        jPanel45 = new javax.swing.JPanel();
        jScrollPane13 = new javax.swing.JScrollPane();
        step3Ref5Q1NotesTA = new javax.swing.JTextArea();
        jPanel46 = new javax.swing.JPanel();
        jScrollPane14 = new javax.swing.JScrollPane();
        step3Ref5Q2TA = new javax.swing.JTextArea();
        jPanel47 = new javax.swing.JPanel();
        step3Ref5Q2rbYes = new javax.swing.JRadioButton();
        step3Ref5Q2rbNo = new javax.swing.JRadioButton();
        step3Ref5Q2rbNA = new javax.swing.JRadioButton();
        step3Ref5Q2rbObs = new javax.swing.JRadioButton();
        jPanel48 = new javax.swing.JPanel();
        jScrollPane15 = new javax.swing.JScrollPane();
        step3Ref5Q2NotesTA = new javax.swing.JTextArea();
        jPanel52 = new javax.swing.JPanel();
        jScrollPane18 = new javax.swing.JScrollPane();
        step3Ref5Q3TA = new javax.swing.JTextArea();
        jPanel53 = new javax.swing.JPanel();
        step3Ref5Q3rbYes = new javax.swing.JRadioButton();
        step3Ref5Q3rbNo = new javax.swing.JRadioButton();
        step3Ref5Q3rbNA = new javax.swing.JRadioButton();
        step3Ref5Q3rbObs = new javax.swing.JRadioButton();
        jPanel54 = new javax.swing.JPanel();
        jScrollPane19 = new javax.swing.JScrollPane();
        step3Ref5Q3NotesTA = new javax.swing.JTextArea();
        jPanel14 = new javax.swing.JPanel();
        step3Ref1Q6TP = new javax.swing.JTabbedPane();
        jPanel55 = new javax.swing.JPanel();
        jScrollPane20 = new javax.swing.JScrollPane();
        step3Ref6Q1TA = new javax.swing.JTextArea();
        jPanel56 = new javax.swing.JPanel();
        step3Ref6Q1rbYes = new javax.swing.JRadioButton();
        step3Ref6Q1rbNo = new javax.swing.JRadioButton();
        step3Ref6Q1rbNA = new javax.swing.JRadioButton();
        step3Ref6Q1rbObs = new javax.swing.JRadioButton();
        jPanel57 = new javax.swing.JPanel();
        jScrollPane21 = new javax.swing.JScrollPane();
        step3Ref6Q1NotesTA = new javax.swing.JTextArea();
        jPanel70 = new javax.swing.JPanel();
        jScrollPane30 = new javax.swing.JScrollPane();
        step3Ref6Q2TA = new javax.swing.JTextArea();
        jPanel71 = new javax.swing.JPanel();
        step3Ref6Q2rbYes = new javax.swing.JRadioButton();
        step3Ref6Q2rbNo = new javax.swing.JRadioButton();
        step3Ref6Q2rbNA = new javax.swing.JRadioButton();
        step3Ref6Q2rbObs = new javax.swing.JRadioButton();
        jPanel72 = new javax.swing.JPanel();
        jScrollPane31 = new javax.swing.JScrollPane();
        step3Ref6Q2NotesTA = new javax.swing.JTextArea();
        jPanel64 = new javax.swing.JPanel();
        jScrollPane26 = new javax.swing.JScrollPane();
        step3Ref6Q3TA = new javax.swing.JTextArea();
        jPanel65 = new javax.swing.JPanel();
        step3Ref6Q3rbYes = new javax.swing.JRadioButton();
        step3Ref6Q3rbNo = new javax.swing.JRadioButton();
        step3Ref6Q3rbNA = new javax.swing.JRadioButton();
        step3Ref6Q3rbObs = new javax.swing.JRadioButton();
        jPanel66 = new javax.swing.JPanel();
        jScrollPane27 = new javax.swing.JScrollPane();
        step3Ref6Q3NotesTA = new javax.swing.JTextArea();
        jPanel67 = new javax.swing.JPanel();
        jScrollPane28 = new javax.swing.JScrollPane();
        step3Ref6Q4TA = new javax.swing.JTextArea();
        jPanel68 = new javax.swing.JPanel();
        step3Ref6Q4rbYes = new javax.swing.JRadioButton();
        step3Ref6Q4rbNo = new javax.swing.JRadioButton();
        step3Ref6Q4rbNA = new javax.swing.JRadioButton();
        step3Ref6Q4rbObs = new javax.swing.JRadioButton();
        jPanel69 = new javax.swing.JPanel();
        jScrollPane29 = new javax.swing.JScrollPane();
        step3Ref6Q4NotesTA = new javax.swing.JTextArea();
        nextButton = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTextArea1 = new javax.swing.JTextArea();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        jMenu2 = new javax.swing.JMenu();
        step3HelpPT1 = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("ISO 17025-2017 Internal Audit Step 3");
        setLocation(new java.awt.Point(500, 200));
        setResizable(false);

        closeButton.setText("Save & Close");
        closeButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                closeButtonActionPerformed(evt);
            }
        });

        previousButton.setText("Previous");
        previousButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                previousButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(previousButton)
                .addGap(191, 191, 191)
                .addComponent(closeButton)
                .addGap(304, 304, 304))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(closeButton)
                    .addComponent(previousButton))
                .addContainerGap())
        );

        step3Ref1tp.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Requirement Reference ", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Times New Roman", 0, 14))); // NOI18N
        step3Ref1tp.setTabLayoutPolicy(javax.swing.JTabbedPane.SCROLL_TAB_LAYOUT);
        step3Ref1tp.setTabPlacement(javax.swing.JTabbedPane.LEFT);
        step3Ref1tp.setAutoscrolls(true);

        step3Ref1Q1TP.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Questions", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Times New Roman", 0, 14))); // NOI18N
        step3Ref1Q1TP.setTabLayoutPolicy(javax.swing.JTabbedPane.SCROLL_TAB_LAYOUT);
        step3Ref1Q1TP.setTabPlacement(javax.swing.JTabbedPane.LEFT);

        step3Ref1Q1TA.setEditable(false);
        step3Ref1Q1TA.setColumns(20);
        step3Ref1Q1TA.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        step3Ref1Q1TA.setLineWrap(true);
        step3Ref1Q1TA.setRows(5);
        step3Ref1Q1TA.setText("Are personnel authorized for their duties, trained on equipment, competent in performance of duties, and familiar with processes?");
        step3Ref1Q1TA.setWrapStyleWord(true);
        jScrollPane2.setViewportView(step3Ref1Q1TA);

        jPanel7.setBorder(javax.swing.BorderFactory.createTitledBorder("Answer Here"));

        buttonGroup1.add(step3Ref1Q1rbYes);
        step3Ref1Q1rbYes.setText("Yes");

        buttonGroup1.add(step3Ref1Q1rbNo);
        step3Ref1Q1rbNo.setText("No");

        buttonGroup1.add(step3Ref1Q1rbNA);
        step3Ref1Q1rbNA.setText("N/A");

        buttonGroup1.add(step3Ref1Q1rbObs);
        step3Ref1Q1rbObs.setSelected(true);
        step3Ref1Q1rbObs.setText("Obs");

        javax.swing.GroupLayout jPanel7Layout = new javax.swing.GroupLayout(jPanel7);
        jPanel7.setLayout(jPanel7Layout);
        jPanel7Layout.setHorizontalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel7Layout.createSequentialGroup()
                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(step3Ref1Q1rbYes)
                    .addComponent(step3Ref1Q1rbNo)
                    .addComponent(step3Ref1Q1rbNA)
                    .addComponent(step3Ref1Q1rbObs))
                .addGap(0, 26, Short.MAX_VALUE))
        );
        jPanel7Layout.setVerticalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel7Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(step3Ref1Q1rbYes)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(step3Ref1Q1rbNo)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(step3Ref1Q1rbNA)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(step3Ref1Q1rbObs)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel6.setBorder(javax.swing.BorderFactory.createTitledBorder("Evidence or Notes Sheet Ref. #"));

        step3Ref1Q1NotesTA.setColumns(20);
        step3Ref1Q1NotesTA.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        step3Ref1Q1NotesTA.setLineWrap(true);
        step3Ref1Q1NotesTA.setRows(5);
        step3Ref1Q1NotesTA.setWrapStyleWord(true);
        jScrollPane3.setViewportView(step3Ref1Q1NotesTA);

        javax.swing.GroupLayout jPanel6Layout = new javax.swing.GroupLayout(jPanel6);
        jPanel6.setLayout(jPanel6Layout);
        jPanel6Layout.setHorizontalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane3)
                .addContainerGap())
        );
        jPanel6Layout.setVerticalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 548, Short.MAX_VALUE)
                        .addGap(18, 18, 18)
                        .addComponent(jPanel7, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(24, 24, 24))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jPanel7, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jScrollPane2))
                .addGap(18, 18, 18)
                .addComponent(jPanel6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(75, Short.MAX_VALUE))
        );

        step3Ref1Q1TP.addTab("Question 1", jPanel4);

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(step3Ref1Q1TP)
                .addContainerGap())
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(step3Ref1Q1TP, javax.swing.GroupLayout.PREFERRED_SIZE, 386, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        step3Ref1tp.addTab("5.5b, 5.6, 6.2", jPanel3);

        step3Ref1Q2TP.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Questions", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Times New Roman", 0, 14))); // NOI18N
        step3Ref1Q2TP.setTabLayoutPolicy(javax.swing.JTabbedPane.SCROLL_TAB_LAYOUT);
        step3Ref1Q2TP.setTabPlacement(javax.swing.JTabbedPane.LEFT);

        step3Ref2Q1TA.setEditable(false);
        step3Ref2Q1TA.setColumns(20);
        step3Ref2Q1TA.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        step3Ref2Q1TA.setLineWrap(true);
        step3Ref2Q1TA.setRows(5);
        step3Ref2Q1TA.setText("Facilities and environment?");
        step3Ref2Q1TA.setWrapStyleWord(true);
        jScrollPane4.setViewportView(step3Ref2Q1TA);

        jPanel9.setBorder(javax.swing.BorderFactory.createTitledBorder("Answer Here"));

        buttonGroup2.add(step3Ref2Q1rbYes);
        step3Ref2Q1rbYes.setText("Yes");

        buttonGroup2.add(step3Ref2Q1rbNo);
        step3Ref2Q1rbNo.setText("No");

        buttonGroup2.add(step3Ref2Q1rbNA);
        step3Ref2Q1rbNA.setSelected(true);
        step3Ref2Q1rbNA.setText("N/A");

        buttonGroup2.add(step3Ref2Q1rbObs);
        step3Ref2Q1rbObs.setText("Obs");

        javax.swing.GroupLayout jPanel9Layout = new javax.swing.GroupLayout(jPanel9);
        jPanel9.setLayout(jPanel9Layout);
        jPanel9Layout.setHorizontalGroup(
            jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel9Layout.createSequentialGroup()
                .addGroup(jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(step3Ref2Q1rbYes)
                    .addComponent(step3Ref2Q1rbNo)
                    .addComponent(step3Ref2Q1rbNA)
                    .addComponent(step3Ref2Q1rbObs))
                .addGap(0, 26, Short.MAX_VALUE))
        );
        jPanel9Layout.setVerticalGroup(
            jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel9Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(step3Ref2Q1rbYes)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(step3Ref2Q1rbNo)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(step3Ref2Q1rbNA, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(step3Ref2Q1rbObs)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel10.setBorder(javax.swing.BorderFactory.createTitledBorder("Evidence or Notes Sheet Ref. #"));

        step3Ref2Q1NotesTA.setColumns(20);
        step3Ref2Q1NotesTA.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        step3Ref2Q1NotesTA.setLineWrap(true);
        step3Ref2Q1NotesTA.setRows(5);
        step3Ref2Q1NotesTA.setWrapStyleWord(true);
        jScrollPane5.setViewportView(step3Ref2Q1NotesTA);

        javax.swing.GroupLayout jPanel10Layout = new javax.swing.GroupLayout(jPanel10);
        jPanel10.setLayout(jPanel10Layout);
        jPanel10Layout.setHorizontalGroup(
            jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel10Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane5, javax.swing.GroupLayout.DEFAULT_SIZE, 615, Short.MAX_VALUE)
                .addContainerGap())
        );
        jPanel10Layout.setVerticalGroup(
            jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel10Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout jPanel8Layout = new javax.swing.GroupLayout(jPanel8);
        jPanel8.setLayout(jPanel8Layout);
        jPanel8Layout.setHorizontalGroup(
            jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel8Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jPanel10, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(jPanel8Layout.createSequentialGroup()
                        .addComponent(jScrollPane4)
                        .addGap(18, 18, 18)
                        .addComponent(jPanel9, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(24, 24, 24))
        );
        jPanel8Layout.setVerticalGroup(
            jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel8Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jPanel9, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jScrollPane4))
                .addGap(18, 18, 18)
                .addComponent(jPanel10, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(88, Short.MAX_VALUE))
        );

        step3Ref1Q2TP.addTab("Question 1", jPanel8);

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel5Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(step3Ref1Q2TP)
                .addContainerGap())
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(step3Ref1Q2TP, javax.swing.GroupLayout.PREFERRED_SIZE, 399, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        step3Ref1tp.addTab("6.3", jPanel5);

        step3Ref1Q3TP.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Questions", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Times New Roman", 0, 14))); // NOI18N
        step3Ref1Q3TP.setTabLayoutPolicy(javax.swing.JTabbedPane.SCROLL_TAB_LAYOUT);
        step3Ref1Q3TP.setTabPlacement(javax.swing.JTabbedPane.LEFT);

        step3Ref3Q1TA.setEditable(false);
        step3Ref3Q1TA.setColumns(20);
        step3Ref3Q1TA.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        step3Ref3Q1TA.setLineWrap(true);
        step3Ref3Q1TA.setRows(5);
        step3Ref3Q1TA.setText("Does the laboratory have equipment required for operation?  Is that equipment capable of achieving the measurement accuracy for laboratory operations; is the equipment calibrated and traceable to SI");
        step3Ref3Q1TA.setWrapStyleWord(true);
        jScrollPane8.setViewportView(step3Ref3Q1TA);

        jPanel38.setBorder(javax.swing.BorderFactory.createTitledBorder("Answer Here"));

        buttonGroup3.add(step3Ref3Q1rbYes);
        step3Ref3Q1rbYes.setText("Yes");

        buttonGroup3.add(step3Ref3Q1rbNo);
        step3Ref3Q1rbNo.setText("No");

        buttonGroup3.add(step3Ref3Q1rbNA);
        step3Ref3Q1rbNA.setSelected(true);
        step3Ref3Q1rbNA.setText("N/A");

        buttonGroup3.add(step3Ref3Q1rbObs);
        step3Ref3Q1rbObs.setText("Obs");

        javax.swing.GroupLayout jPanel38Layout = new javax.swing.GroupLayout(jPanel38);
        jPanel38.setLayout(jPanel38Layout);
        jPanel38Layout.setHorizontalGroup(
            jPanel38Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel38Layout.createSequentialGroup()
                .addGroup(jPanel38Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(step3Ref3Q1rbYes)
                    .addComponent(step3Ref3Q1rbNo)
                    .addComponent(step3Ref3Q1rbNA)
                    .addComponent(step3Ref3Q1rbObs))
                .addGap(0, 26, Short.MAX_VALUE))
        );
        jPanel38Layout.setVerticalGroup(
            jPanel38Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel38Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(step3Ref3Q1rbYes)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(step3Ref3Q1rbNo)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(step3Ref3Q1rbNA)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(step3Ref3Q1rbObs)
                .addContainerGap(8, Short.MAX_VALUE))
        );

        jPanel39.setBorder(javax.swing.BorderFactory.createTitledBorder("Evidence or Notes Sheet Ref. #"));

        step3Ref3Q1NotesTA.setColumns(20);
        step3Ref3Q1NotesTA.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        step3Ref3Q1NotesTA.setLineWrap(true);
        step3Ref3Q1NotesTA.setRows(5);
        step3Ref3Q1NotesTA.setWrapStyleWord(true);
        jScrollPane9.setViewportView(step3Ref3Q1NotesTA);

        javax.swing.GroupLayout jPanel39Layout = new javax.swing.GroupLayout(jPanel39);
        jPanel39.setLayout(jPanel39Layout);
        jPanel39Layout.setHorizontalGroup(
            jPanel39Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel39Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane9, javax.swing.GroupLayout.DEFAULT_SIZE, 615, Short.MAX_VALUE)
                .addContainerGap())
        );
        jPanel39Layout.setVerticalGroup(
            jPanel39Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel39Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane9, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout jPanel37Layout = new javax.swing.GroupLayout(jPanel37);
        jPanel37.setLayout(jPanel37Layout);
        jPanel37Layout.setHorizontalGroup(
            jPanel37Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel37Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel37Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jPanel39, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(jPanel37Layout.createSequentialGroup()
                        .addComponent(jScrollPane8)
                        .addGap(18, 18, 18)
                        .addComponent(jPanel38, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(24, 24, 24))
        );
        jPanel37Layout.setVerticalGroup(
            jPanel37Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel37Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel37Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jPanel38, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jScrollPane8))
                .addGap(18, 18, 18)
                .addComponent(jPanel39, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(87, Short.MAX_VALUE))
        );

        step3Ref1Q3TP.addTab("Question 1", jPanel37);

        javax.swing.GroupLayout jPanel11Layout = new javax.swing.GroupLayout(jPanel11);
        jPanel11.setLayout(jPanel11Layout);
        jPanel11Layout.setHorizontalGroup(
            jPanel11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel11Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(step3Ref1Q3TP)
                .addContainerGap())
        );
        jPanel11Layout.setVerticalGroup(
            jPanel11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel11Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(step3Ref1Q3TP, javax.swing.GroupLayout.PREFERRED_SIZE, 398, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        step3Ref1tp.addTab("6.4", jPanel11);

        step3Ref1Q4TP.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Questions", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Times New Roman", 0, 14))); // NOI18N
        step3Ref1Q4TP.setTabLayoutPolicy(javax.swing.JTabbedPane.SCROLL_TAB_LAYOUT);
        step3Ref1Q4TP.setTabPlacement(javax.swing.JTabbedPane.LEFT);

        step3Ref4Q1TA.setEditable(false);
        step3Ref4Q1TA.setColumns(20);
        step3Ref4Q1TA.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        step3Ref4Q1TA.setLineWrap(true);
        step3Ref4Q1TA.setRows(5);
        step3Ref4Q1TA.setText("Is laboratory equipment acceptance tested upon receipt from vendor?  Are intermediate checks performed upon transport?");
        step3Ref4Q1TA.setWrapStyleWord(true);
        jScrollPane10.setViewportView(step3Ref4Q1TA);

        jPanel41.setBorder(javax.swing.BorderFactory.createTitledBorder("Answer Here"));

        buttonGroup4.add(step3Ref4Q1rbYes);
        step3Ref4Q1rbYes.setText("Yes");

        buttonGroup4.add(step3Ref4Q1rbNo);
        step3Ref4Q1rbNo.setText("No");

        buttonGroup4.add(step3Ref4Q1rbNA);
        step3Ref4Q1rbNA.setSelected(true);
        step3Ref4Q1rbNA.setText("N/A");

        buttonGroup4.add(step3Ref4Q1rbObs);
        step3Ref4Q1rbObs.setText("Obs");

        javax.swing.GroupLayout jPanel41Layout = new javax.swing.GroupLayout(jPanel41);
        jPanel41.setLayout(jPanel41Layout);
        jPanel41Layout.setHorizontalGroup(
            jPanel41Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel41Layout.createSequentialGroup()
                .addGroup(jPanel41Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(step3Ref4Q1rbYes)
                    .addComponent(step3Ref4Q1rbNo)
                    .addComponent(step3Ref4Q1rbNA)
                    .addComponent(step3Ref4Q1rbObs))
                .addGap(0, 26, Short.MAX_VALUE))
        );
        jPanel41Layout.setVerticalGroup(
            jPanel41Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel41Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(step3Ref4Q1rbYes)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(step3Ref4Q1rbNo)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(step3Ref4Q1rbNA)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(step3Ref4Q1rbObs)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel42.setBorder(javax.swing.BorderFactory.createTitledBorder("Evidence or Notes Sheet Ref. #"));

        step3Ref4Q1NotesTA.setColumns(20);
        step3Ref4Q1NotesTA.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        step3Ref4Q1NotesTA.setLineWrap(true);
        step3Ref4Q1NotesTA.setRows(5);
        step3Ref4Q1NotesTA.setWrapStyleWord(true);
        jScrollPane11.setViewportView(step3Ref4Q1NotesTA);

        javax.swing.GroupLayout jPanel42Layout = new javax.swing.GroupLayout(jPanel42);
        jPanel42.setLayout(jPanel42Layout);
        jPanel42Layout.setHorizontalGroup(
            jPanel42Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel42Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane11, javax.swing.GroupLayout.DEFAULT_SIZE, 615, Short.MAX_VALUE)
                .addContainerGap())
        );
        jPanel42Layout.setVerticalGroup(
            jPanel42Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel42Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane11, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout jPanel40Layout = new javax.swing.GroupLayout(jPanel40);
        jPanel40.setLayout(jPanel40Layout);
        jPanel40Layout.setHorizontalGroup(
            jPanel40Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel40Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel40Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jPanel42, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(jPanel40Layout.createSequentialGroup()
                        .addComponent(jScrollPane10)
                        .addGap(18, 18, 18)
                        .addComponent(jPanel41, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(24, 24, 24))
        );
        jPanel40Layout.setVerticalGroup(
            jPanel40Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel40Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel40Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jPanel41, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jScrollPane10))
                .addGap(18, 18, 18)
                .addComponent(jPanel42, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(146, Short.MAX_VALUE))
        );

        step3Ref1Q4TP.addTab("Question 1", jPanel40);

        javax.swing.GroupLayout jPanel12Layout = new javax.swing.GroupLayout(jPanel12);
        jPanel12.setLayout(jPanel12Layout);
        jPanel12Layout.setHorizontalGroup(
            jPanel12Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel12Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(step3Ref1Q4TP)
                .addContainerGap())
        );
        jPanel12Layout.setVerticalGroup(
            jPanel12Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel12Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(step3Ref1Q4TP, javax.swing.GroupLayout.PREFERRED_SIZE, 414, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        step3Ref1tp.addTab("6.4", jPanel12);

        step3Ref1Q5TP.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Questions", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Times New Roman", 0, 14))); // NOI18N
        step3Ref1Q5TP.setTabLayoutPolicy(javax.swing.JTabbedPane.SCROLL_TAB_LAYOUT);
        step3Ref1Q5TP.setTabPlacement(javax.swing.JTabbedPane.LEFT);

        step3Ref5Q1TA.setEditable(false);
        step3Ref5Q1TA.setColumns(20);
        step3Ref5Q1TA.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        step3Ref5Q1TA.setLineWrap(true);
        step3Ref5Q1TA.setRows(5);
        step3Ref5Q1TA.setText("Competent vendors?\n\n");
        step3Ref5Q1TA.setWrapStyleWord(true);
        jScrollPane12.setViewportView(step3Ref5Q1TA);

        jPanel44.setBorder(javax.swing.BorderFactory.createTitledBorder("Answer Here"));

        buttonGroup5.add(step3Ref5Q1rbYes);
        step3Ref5Q1rbYes.setText("Yes");

        buttonGroup5.add(step3Ref5Q1rbNo);
        step3Ref5Q1rbNo.setText("No");

        buttonGroup5.add(step3Ref5Q1rbNA);
        step3Ref5Q1rbNA.setSelected(true);
        step3Ref5Q1rbNA.setText("N/A");

        buttonGroup5.add(step3Ref5Q1rbObs);
        step3Ref5Q1rbObs.setText("Obs");

        javax.swing.GroupLayout jPanel44Layout = new javax.swing.GroupLayout(jPanel44);
        jPanel44.setLayout(jPanel44Layout);
        jPanel44Layout.setHorizontalGroup(
            jPanel44Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel44Layout.createSequentialGroup()
                .addGroup(jPanel44Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(step3Ref5Q1rbYes)
                    .addComponent(step3Ref5Q1rbNo)
                    .addComponent(step3Ref5Q1rbNA)
                    .addComponent(step3Ref5Q1rbObs))
                .addGap(0, 26, Short.MAX_VALUE))
        );
        jPanel44Layout.setVerticalGroup(
            jPanel44Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel44Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(step3Ref5Q1rbYes)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(step3Ref5Q1rbNo)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(step3Ref5Q1rbNA)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(step3Ref5Q1rbObs)
                .addContainerGap(10, Short.MAX_VALUE))
        );

        jPanel45.setBorder(javax.swing.BorderFactory.createTitledBorder("Evidence or Notes Sheet Ref. #"));

        step3Ref5Q1NotesTA.setColumns(20);
        step3Ref5Q1NotesTA.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        step3Ref5Q1NotesTA.setLineWrap(true);
        step3Ref5Q1NotesTA.setRows(5);
        step3Ref5Q1NotesTA.setWrapStyleWord(true);
        jScrollPane13.setViewportView(step3Ref5Q1NotesTA);

        javax.swing.GroupLayout jPanel45Layout = new javax.swing.GroupLayout(jPanel45);
        jPanel45.setLayout(jPanel45Layout);
        jPanel45Layout.setHorizontalGroup(
            jPanel45Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel45Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane13, javax.swing.GroupLayout.DEFAULT_SIZE, 541, Short.MAX_VALUE)
                .addContainerGap())
        );
        jPanel45Layout.setVerticalGroup(
            jPanel45Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel45Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane13, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout jPanel43Layout = new javax.swing.GroupLayout(jPanel43);
        jPanel43.setLayout(jPanel43Layout);
        jPanel43Layout.setHorizontalGroup(
            jPanel43Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel43Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel43Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jPanel45, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(jPanel43Layout.createSequentialGroup()
                        .addComponent(jScrollPane12)
                        .addGap(18, 18, 18)
                        .addComponent(jPanel44, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(24, 24, 24))
        );
        jPanel43Layout.setVerticalGroup(
            jPanel43Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel43Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel43Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jPanel44, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jScrollPane12))
                .addGap(18, 18, 18)
                .addComponent(jPanel45, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(87, Short.MAX_VALUE))
        );

        step3Ref1Q5TP.addTab("Metrological Traceability 1 ", jPanel43);

        step3Ref5Q2TA.setEditable(false);
        step3Ref5Q2TA.setColumns(20);
        step3Ref5Q2TA.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        step3Ref5Q2TA.setLineWrap(true);
        step3Ref5Q2TA.setRows(5);
        step3Ref5Q2TA.setText("Traceable to SI");
        step3Ref5Q2TA.setWrapStyleWord(true);
        jScrollPane14.setViewportView(step3Ref5Q2TA);

        jPanel47.setBorder(javax.swing.BorderFactory.createTitledBorder("Answer Here"));

        buttonGroup6.add(step3Ref5Q2rbYes);
        step3Ref5Q2rbYes.setText("Yes");

        buttonGroup6.add(step3Ref5Q2rbNo);
        step3Ref5Q2rbNo.setText("No");

        buttonGroup6.add(step3Ref5Q2rbNA);
        step3Ref5Q2rbNA.setSelected(true);
        step3Ref5Q2rbNA.setText("N/A");

        buttonGroup6.add(step3Ref5Q2rbObs);
        step3Ref5Q2rbObs.setText("Obs");

        javax.swing.GroupLayout jPanel47Layout = new javax.swing.GroupLayout(jPanel47);
        jPanel47.setLayout(jPanel47Layout);
        jPanel47Layout.setHorizontalGroup(
            jPanel47Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel47Layout.createSequentialGroup()
                .addGroup(jPanel47Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(step3Ref5Q2rbYes)
                    .addComponent(step3Ref5Q2rbNo)
                    .addComponent(step3Ref5Q2rbNA)
                    .addComponent(step3Ref5Q2rbObs))
                .addGap(0, 26, Short.MAX_VALUE))
        );
        jPanel47Layout.setVerticalGroup(
            jPanel47Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel47Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(step3Ref5Q2rbYes)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(step3Ref5Q2rbNo)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(step3Ref5Q2rbNA)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(step3Ref5Q2rbObs)
                .addContainerGap(10, Short.MAX_VALUE))
        );

        jPanel48.setBorder(javax.swing.BorderFactory.createTitledBorder("Evidence or Notes Sheet Ref. #"));

        step3Ref5Q2NotesTA.setColumns(20);
        step3Ref5Q2NotesTA.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        step3Ref5Q2NotesTA.setRows(5);
        jScrollPane15.setViewportView(step3Ref5Q2NotesTA);

        javax.swing.GroupLayout jPanel48Layout = new javax.swing.GroupLayout(jPanel48);
        jPanel48.setLayout(jPanel48Layout);
        jPanel48Layout.setHorizontalGroup(
            jPanel48Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel48Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane15, javax.swing.GroupLayout.DEFAULT_SIZE, 541, Short.MAX_VALUE)
                .addContainerGap())
        );
        jPanel48Layout.setVerticalGroup(
            jPanel48Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel48Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane15, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout jPanel46Layout = new javax.swing.GroupLayout(jPanel46);
        jPanel46.setLayout(jPanel46Layout);
        jPanel46Layout.setHorizontalGroup(
            jPanel46Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel46Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel46Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jPanel48, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(jPanel46Layout.createSequentialGroup()
                        .addComponent(jScrollPane14)
                        .addGap(18, 18, 18)
                        .addComponent(jPanel47, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(24, 24, 24))
        );
        jPanel46Layout.setVerticalGroup(
            jPanel46Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel46Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel46Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jPanel47, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jScrollPane14))
                .addGap(18, 18, 18)
                .addComponent(jPanel48, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(87, Short.MAX_VALUE))
        );

        step3Ref1Q5TP.addTab("Metrological Traceability 2 ", jPanel46);

        step3Ref5Q3TA.setEditable(false);
        step3Ref5Q3TA.setColumns(20);
        step3Ref5Q3TA.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        step3Ref5Q3TA.setLineWrap(true);
        step3Ref5Q3TA.setRows(5);
        step3Ref5Q3TA.setText("Reviewed for accuracy/uncertainty and metrological process?");
        step3Ref5Q3TA.setWrapStyleWord(true);
        jScrollPane18.setViewportView(step3Ref5Q3TA);

        jPanel53.setBorder(javax.swing.BorderFactory.createTitledBorder("Answer Here"));

        buttonGroup7.add(step3Ref5Q3rbYes);
        step3Ref5Q3rbYes.setText("Yes");

        buttonGroup7.add(step3Ref5Q3rbNo);
        step3Ref5Q3rbNo.setText("No");

        buttonGroup7.add(step3Ref5Q3rbNA);
        step3Ref5Q3rbNA.setSelected(true);
        step3Ref5Q3rbNA.setText("N/A");

        buttonGroup7.add(step3Ref5Q3rbObs);
        step3Ref5Q3rbObs.setText("Obs");

        javax.swing.GroupLayout jPanel53Layout = new javax.swing.GroupLayout(jPanel53);
        jPanel53.setLayout(jPanel53Layout);
        jPanel53Layout.setHorizontalGroup(
            jPanel53Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel53Layout.createSequentialGroup()
                .addGroup(jPanel53Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(step3Ref5Q3rbYes)
                    .addComponent(step3Ref5Q3rbNo)
                    .addComponent(step3Ref5Q3rbNA)
                    .addComponent(step3Ref5Q3rbObs))
                .addGap(0, 26, Short.MAX_VALUE))
        );
        jPanel53Layout.setVerticalGroup(
            jPanel53Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel53Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(step3Ref5Q3rbYes)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(step3Ref5Q3rbNo)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(step3Ref5Q3rbNA)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(step3Ref5Q3rbObs)
                .addContainerGap(10, Short.MAX_VALUE))
        );

        jPanel54.setBorder(javax.swing.BorderFactory.createTitledBorder("Evidence or Notes Sheet Ref. #"));

        step3Ref5Q3NotesTA.setColumns(20);
        step3Ref5Q3NotesTA.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        step3Ref5Q3NotesTA.setRows(5);
        jScrollPane19.setViewportView(step3Ref5Q3NotesTA);

        javax.swing.GroupLayout jPanel54Layout = new javax.swing.GroupLayout(jPanel54);
        jPanel54.setLayout(jPanel54Layout);
        jPanel54Layout.setHorizontalGroup(
            jPanel54Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel54Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane19, javax.swing.GroupLayout.DEFAULT_SIZE, 541, Short.MAX_VALUE)
                .addContainerGap())
        );
        jPanel54Layout.setVerticalGroup(
            jPanel54Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel54Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane19, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout jPanel52Layout = new javax.swing.GroupLayout(jPanel52);
        jPanel52.setLayout(jPanel52Layout);
        jPanel52Layout.setHorizontalGroup(
            jPanel52Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel52Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel52Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jPanel54, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(jPanel52Layout.createSequentialGroup()
                        .addComponent(jScrollPane18)
                        .addGap(18, 18, 18)
                        .addComponent(jPanel53, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(24, 24, 24))
        );
        jPanel52Layout.setVerticalGroup(
            jPanel52Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel52Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel52Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jPanel53, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jScrollPane18))
                .addGap(18, 18, 18)
                .addComponent(jPanel54, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(87, Short.MAX_VALUE))
        );

        step3Ref1Q5TP.addTab("Metrological Traceability 3", jPanel52);

        javax.swing.GroupLayout jPanel13Layout = new javax.swing.GroupLayout(jPanel13);
        jPanel13.setLayout(jPanel13Layout);
        jPanel13Layout.setHorizontalGroup(
            jPanel13Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel13Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(step3Ref1Q5TP)
                .addContainerGap())
        );
        jPanel13Layout.setVerticalGroup(
            jPanel13Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel13Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(step3Ref1Q5TP, javax.swing.GroupLayout.PREFERRED_SIZE, 398, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        step3Ref1tp.addTab("6.5", jPanel13);

        step3Ref1Q6TP.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Questions", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Times New Roman", 0, 14))); // NOI18N
        step3Ref1Q6TP.setTabLayoutPolicy(javax.swing.JTabbedPane.SCROLL_TAB_LAYOUT);
        step3Ref1Q6TP.setTabPlacement(javax.swing.JTabbedPane.LEFT);

        step3Ref6Q1TA.setEditable(false);
        step3Ref6Q1TA.setColumns(20);
        step3Ref6Q1TA.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        step3Ref6Q1TA.setLineWrap(true);
        step3Ref6Q1TA.setRows(5);
        step3Ref6Q1TA.setText("Authorized Vendor List");
        step3Ref6Q1TA.setWrapStyleWord(true);
        jScrollPane20.setViewportView(step3Ref6Q1TA);

        jPanel56.setBorder(javax.swing.BorderFactory.createTitledBorder("Answer Here"));

        buttonGroup8.add(step3Ref6Q1rbYes);
        step3Ref6Q1rbYes.setText("Yes");

        buttonGroup8.add(step3Ref6Q1rbNo);
        step3Ref6Q1rbNo.setText("No");

        buttonGroup8.add(step3Ref6Q1rbNA);
        step3Ref6Q1rbNA.setSelected(true);
        step3Ref6Q1rbNA.setText("N/A");

        buttonGroup8.add(step3Ref6Q1rbObs);
        step3Ref6Q1rbObs.setText("Obs");

        javax.swing.GroupLayout jPanel56Layout = new javax.swing.GroupLayout(jPanel56);
        jPanel56.setLayout(jPanel56Layout);
        jPanel56Layout.setHorizontalGroup(
            jPanel56Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel56Layout.createSequentialGroup()
                .addGroup(jPanel56Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(step3Ref6Q1rbYes)
                    .addComponent(step3Ref6Q1rbNo)
                    .addComponent(step3Ref6Q1rbNA)
                    .addComponent(step3Ref6Q1rbObs))
                .addGap(0, 26, Short.MAX_VALUE))
        );
        jPanel56Layout.setVerticalGroup(
            jPanel56Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel56Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(step3Ref6Q1rbYes)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(step3Ref6Q1rbNo)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(step3Ref6Q1rbNA)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(step3Ref6Q1rbObs)
                .addContainerGap(10, Short.MAX_VALUE))
        );

        jPanel57.setBorder(javax.swing.BorderFactory.createTitledBorder("Evidence or Notes Sheet Ref. #"));

        step3Ref6Q1NotesTA.setColumns(20);
        step3Ref6Q1NotesTA.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        step3Ref6Q1NotesTA.setRows(5);
        jScrollPane21.setViewportView(step3Ref6Q1NotesTA);

        javax.swing.GroupLayout jPanel57Layout = new javax.swing.GroupLayout(jPanel57);
        jPanel57.setLayout(jPanel57Layout);
        jPanel57Layout.setHorizontalGroup(
            jPanel57Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel57Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane21, javax.swing.GroupLayout.DEFAULT_SIZE, 574, Short.MAX_VALUE)
                .addContainerGap())
        );
        jPanel57Layout.setVerticalGroup(
            jPanel57Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel57Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane21, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout jPanel55Layout = new javax.swing.GroupLayout(jPanel55);
        jPanel55.setLayout(jPanel55Layout);
        jPanel55Layout.setHorizontalGroup(
            jPanel55Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel55Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel55Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jPanel57, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(jPanel55Layout.createSequentialGroup()
                        .addComponent(jScrollPane20)
                        .addGap(18, 18, 18)
                        .addComponent(jPanel56, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(24, 24, 24))
        );
        jPanel55Layout.setVerticalGroup(
            jPanel55Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel55Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel55Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jPanel56, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jScrollPane20))
                .addGap(18, 18, 18)
                .addComponent(jPanel57, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(102, Short.MAX_VALUE))
        );

        step3Ref1Q6TP.addTab("External Vendors 1 ", jPanel55);

        step3Ref6Q2TA.setEditable(false);
        step3Ref6Q2TA.setColumns(20);
        step3Ref6Q2TA.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        step3Ref6Q2TA.setLineWrap(true);
        step3Ref6Q2TA.setRows(5);
        step3Ref6Q2TA.setText("Annual Review");
        step3Ref6Q2TA.setWrapStyleWord(true);
        jScrollPane30.setViewportView(step3Ref6Q2TA);

        jPanel71.setBorder(javax.swing.BorderFactory.createTitledBorder("Answer Here"));

        buttonGroup9.add(step3Ref6Q2rbYes);
        step3Ref6Q2rbYes.setText("Yes");

        buttonGroup9.add(step3Ref6Q2rbNo);
        step3Ref6Q2rbNo.setText("No");

        buttonGroup9.add(step3Ref6Q2rbNA);
        step3Ref6Q2rbNA.setSelected(true);
        step3Ref6Q2rbNA.setText("N/A");

        buttonGroup9.add(step3Ref6Q2rbObs);
        step3Ref6Q2rbObs.setText("Obs");

        javax.swing.GroupLayout jPanel71Layout = new javax.swing.GroupLayout(jPanel71);
        jPanel71.setLayout(jPanel71Layout);
        jPanel71Layout.setHorizontalGroup(
            jPanel71Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel71Layout.createSequentialGroup()
                .addGroup(jPanel71Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(step3Ref6Q2rbYes)
                    .addComponent(step3Ref6Q2rbNo)
                    .addComponent(step3Ref6Q2rbNA)
                    .addComponent(step3Ref6Q2rbObs))
                .addGap(0, 26, Short.MAX_VALUE))
        );
        jPanel71Layout.setVerticalGroup(
            jPanel71Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel71Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(step3Ref6Q2rbYes)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(step3Ref6Q2rbNo)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(step3Ref6Q2rbNA)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(step3Ref6Q2rbObs)
                .addContainerGap(10, Short.MAX_VALUE))
        );

        jPanel72.setBorder(javax.swing.BorderFactory.createTitledBorder("Evidence or Notes Sheet Ref. #"));

        step3Ref6Q2NotesTA.setColumns(20);
        step3Ref6Q2NotesTA.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        step3Ref6Q2NotesTA.setRows(5);
        jScrollPane31.setViewportView(step3Ref6Q2NotesTA);

        javax.swing.GroupLayout jPanel72Layout = new javax.swing.GroupLayout(jPanel72);
        jPanel72.setLayout(jPanel72Layout);
        jPanel72Layout.setHorizontalGroup(
            jPanel72Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel72Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane31, javax.swing.GroupLayout.DEFAULT_SIZE, 574, Short.MAX_VALUE)
                .addContainerGap())
        );
        jPanel72Layout.setVerticalGroup(
            jPanel72Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel72Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane31, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout jPanel70Layout = new javax.swing.GroupLayout(jPanel70);
        jPanel70.setLayout(jPanel70Layout);
        jPanel70Layout.setHorizontalGroup(
            jPanel70Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel70Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel70Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jPanel72, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(jPanel70Layout.createSequentialGroup()
                        .addComponent(jScrollPane30)
                        .addGap(18, 18, 18)
                        .addComponent(jPanel71, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(24, 24, 24))
        );
        jPanel70Layout.setVerticalGroup(
            jPanel70Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel70Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel70Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jPanel71, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jScrollPane30))
                .addGap(18, 18, 18)
                .addComponent(jPanel72, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(102, Short.MAX_VALUE))
        );

        step3Ref1Q6TP.addTab("External Vendors 2", jPanel70);

        step3Ref6Q3TA.setEditable(false);
        step3Ref6Q3TA.setColumns(20);
        step3Ref6Q3TA.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        step3Ref6Q3TA.setLineWrap(true);
        step3Ref6Q3TA.setRows(5);
        step3Ref6Q3TA.setText("SCAR actions when problems identified");
        step3Ref6Q3TA.setWrapStyleWord(true);
        jScrollPane26.setViewportView(step3Ref6Q3TA);

        jPanel65.setBorder(javax.swing.BorderFactory.createTitledBorder("Answer Here"));

        buttonGroup10.add(step3Ref6Q3rbYes);
        step3Ref6Q3rbYes.setText("Yes");

        buttonGroup10.add(step3Ref6Q3rbNo);
        step3Ref6Q3rbNo.setText("No");

        buttonGroup10.add(step3Ref6Q3rbNA);
        step3Ref6Q3rbNA.setSelected(true);
        step3Ref6Q3rbNA.setText("N/A");

        buttonGroup10.add(step3Ref6Q3rbObs);
        step3Ref6Q3rbObs.setText("Obs");

        javax.swing.GroupLayout jPanel65Layout = new javax.swing.GroupLayout(jPanel65);
        jPanel65.setLayout(jPanel65Layout);
        jPanel65Layout.setHorizontalGroup(
            jPanel65Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel65Layout.createSequentialGroup()
                .addGroup(jPanel65Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(step3Ref6Q3rbYes)
                    .addComponent(step3Ref6Q3rbNo)
                    .addComponent(step3Ref6Q3rbNA)
                    .addComponent(step3Ref6Q3rbObs))
                .addGap(0, 26, Short.MAX_VALUE))
        );
        jPanel65Layout.setVerticalGroup(
            jPanel65Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel65Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(step3Ref6Q3rbYes)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(step3Ref6Q3rbNo)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(step3Ref6Q3rbNA)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(step3Ref6Q3rbObs)
                .addContainerGap(10, Short.MAX_VALUE))
        );

        jPanel66.setBorder(javax.swing.BorderFactory.createTitledBorder("Evidence or Notes Sheet Ref. #"));

        step3Ref6Q3NotesTA.setColumns(20);
        step3Ref6Q3NotesTA.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        step3Ref6Q3NotesTA.setRows(5);
        jScrollPane27.setViewportView(step3Ref6Q3NotesTA);

        javax.swing.GroupLayout jPanel66Layout = new javax.swing.GroupLayout(jPanel66);
        jPanel66.setLayout(jPanel66Layout);
        jPanel66Layout.setHorizontalGroup(
            jPanel66Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel66Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane27, javax.swing.GroupLayout.DEFAULT_SIZE, 574, Short.MAX_VALUE)
                .addContainerGap())
        );
        jPanel66Layout.setVerticalGroup(
            jPanel66Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel66Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane27, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout jPanel64Layout = new javax.swing.GroupLayout(jPanel64);
        jPanel64.setLayout(jPanel64Layout);
        jPanel64Layout.setHorizontalGroup(
            jPanel64Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel64Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel64Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jPanel66, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(jPanel64Layout.createSequentialGroup()
                        .addComponent(jScrollPane26)
                        .addGap(18, 18, 18)
                        .addComponent(jPanel65, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(24, 24, 24))
        );
        jPanel64Layout.setVerticalGroup(
            jPanel64Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel64Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel64Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jPanel65, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jScrollPane26))
                .addGap(18, 18, 18)
                .addComponent(jPanel66, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(102, Short.MAX_VALUE))
        );

        step3Ref1Q6TP.addTab("External Vendors 3", jPanel64);

        step3Ref6Q4TA.setEditable(false);
        step3Ref6Q4TA.setColumns(20);
        step3Ref6Q4TA.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        step3Ref6Q4TA.setLineWrap(true);
        step3Ref6Q4TA.setRows(5);
        step3Ref6Q4TA.setText("Documentation for selection?");
        step3Ref6Q4TA.setWrapStyleWord(true);
        jScrollPane28.setViewportView(step3Ref6Q4TA);

        jPanel68.setBorder(javax.swing.BorderFactory.createTitledBorder("Answer Here"));

        buttonGroup11.add(step3Ref6Q4rbYes);
        step3Ref6Q4rbYes.setText("Yes");

        buttonGroup11.add(step3Ref6Q4rbNo);
        step3Ref6Q4rbNo.setText("No");

        buttonGroup11.add(step3Ref6Q4rbNA);
        step3Ref6Q4rbNA.setSelected(true);
        step3Ref6Q4rbNA.setText("N/A");

        buttonGroup11.add(step3Ref6Q4rbObs);
        step3Ref6Q4rbObs.setText("Obs");

        javax.swing.GroupLayout jPanel68Layout = new javax.swing.GroupLayout(jPanel68);
        jPanel68.setLayout(jPanel68Layout);
        jPanel68Layout.setHorizontalGroup(
            jPanel68Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel68Layout.createSequentialGroup()
                .addGroup(jPanel68Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(step3Ref6Q4rbYes)
                    .addComponent(step3Ref6Q4rbNo)
                    .addComponent(step3Ref6Q4rbNA)
                    .addComponent(step3Ref6Q4rbObs))
                .addGap(0, 26, Short.MAX_VALUE))
        );
        jPanel68Layout.setVerticalGroup(
            jPanel68Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel68Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(step3Ref6Q4rbYes)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(step3Ref6Q4rbNo)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(step3Ref6Q4rbNA)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(step3Ref6Q4rbObs)
                .addContainerGap(10, Short.MAX_VALUE))
        );

        jPanel69.setBorder(javax.swing.BorderFactory.createTitledBorder("Evidence or Notes Sheet Ref. #"));

        step3Ref6Q4NotesTA.setColumns(20);
        step3Ref6Q4NotesTA.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        step3Ref6Q4NotesTA.setLineWrap(true);
        step3Ref6Q4NotesTA.setRows(5);
        step3Ref6Q4NotesTA.setWrapStyleWord(true);
        jScrollPane29.setViewportView(step3Ref6Q4NotesTA);

        javax.swing.GroupLayout jPanel69Layout = new javax.swing.GroupLayout(jPanel69);
        jPanel69.setLayout(jPanel69Layout);
        jPanel69Layout.setHorizontalGroup(
            jPanel69Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel69Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane29, javax.swing.GroupLayout.DEFAULT_SIZE, 574, Short.MAX_VALUE)
                .addContainerGap())
        );
        jPanel69Layout.setVerticalGroup(
            jPanel69Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel69Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane29, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout jPanel67Layout = new javax.swing.GroupLayout(jPanel67);
        jPanel67.setLayout(jPanel67Layout);
        jPanel67Layout.setHorizontalGroup(
            jPanel67Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel67Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel67Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jPanel69, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(jPanel67Layout.createSequentialGroup()
                        .addComponent(jScrollPane28)
                        .addGap(18, 18, 18)
                        .addComponent(jPanel68, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(24, 24, 24))
        );
        jPanel67Layout.setVerticalGroup(
            jPanel67Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel67Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel67Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jPanel68, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jScrollPane28))
                .addGap(18, 18, 18)
                .addComponent(jPanel69, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(102, Short.MAX_VALUE))
        );

        step3Ref1Q6TP.addTab("External Vendors 4", jPanel67);

        nextButton.setText("Next & Save");
        nextButton.setToolTipText("");
        nextButton.setActionCommand("");
        nextButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                nextButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel14Layout = new javax.swing.GroupLayout(jPanel14);
        jPanel14.setLayout(jPanel14Layout);
        jPanel14Layout.setHorizontalGroup(
            jPanel14Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel14Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(step3Ref1Q6TP)
                .addContainerGap())
            .addGroup(jPanel14Layout.createSequentialGroup()
                .addGap(285, 285, 285)
                .addComponent(nextButton)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel14Layout.setVerticalGroup(
            jPanel14Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel14Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(step3Ref1Q6TP, javax.swing.GroupLayout.PREFERRED_SIZE, 413, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(nextButton)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        step3Ref1tp.addTab("6.6", jPanel14);

        jTextArea1.setEditable(false);
        jTextArea1.setBackground(new java.awt.Color(240, 240, 240));
        jTextArea1.setColumns(20);
        jTextArea1.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        jTextArea1.setLineWrap(true);
        jTextArea1.setRows(2);
        jTextArea1.setTabSize(4);
        jTextArea1.setText("Compare the requirements of ISO 17025-2017, the QMS Manual and other documentation against what employees are actually doing in everyday practice. ");
        jTextArea1.setWrapStyleWord(true);
        jScrollPane1.setViewportView(jTextArea1);

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1)
                    .addComponent(step3Ref1tp, javax.swing.GroupLayout.Alignment.TRAILING))
                .addContainerGap())
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(step3Ref1tp, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(23, Short.MAX_VALUE))
        );

        jMenu1.setText("File");
        jMenuBar1.add(jMenu1);

        jMenu2.setText("Help");

        step3HelpPT1.setText("Help");
        step3HelpPT1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                step3HelpPT1ActionPerformed(evt);
            }
        });
        jMenu2.add(step3HelpPT1);

        jMenuBar1.add(jMenu2);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(24, 24, 24)
                        .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void closeButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_closeButtonActionPerformed
        // TODO add your handling code here:
        dispose();
    }//GEN-LAST:event_closeButtonActionPerformed

    private void nextButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_nextButtonActionPerformed
        // TODO add your handling code here:
        Step3Ref7 ref7 = new Step3Ref7();
        ref7.setVisible(true);
        dispose();
    }//GEN-LAST:event_nextButtonActionPerformed

    private void previousButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_previousButtonActionPerformed
        // TODO add your handling code here:
        Step2 ch2 = new Step2();
        ch2.setVisible(true);
        dispose();
    }//GEN-LAST:event_previousButtonActionPerformed

    private void step3HelpPT1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_step3HelpPT1ActionPerformed
        // TODO add your handling code here:
        Helpform hf = new Helpform();
        hf.setVisible(true);
        hf.helpLabel.setText("How to complete Step 3");
        hf.helpTextArea.setText("This is where you place instructions on how to complete step 3.\n\n" +
                                " Step 3 -> 7.7 -> Question 6 missing but has 6 answers.");
    }//GEN-LAST:event_step3HelpPT1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Step3.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Step3.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Step3.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Step3.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Step3().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.ButtonGroup buttonGroup10;
    private javax.swing.ButtonGroup buttonGroup11;
    private javax.swing.ButtonGroup buttonGroup2;
    private javax.swing.ButtonGroup buttonGroup3;
    private javax.swing.ButtonGroup buttonGroup4;
    private javax.swing.ButtonGroup buttonGroup5;
    private javax.swing.ButtonGroup buttonGroup6;
    private javax.swing.ButtonGroup buttonGroup7;
    private javax.swing.ButtonGroup buttonGroup8;
    private javax.swing.ButtonGroup buttonGroup9;
    private javax.swing.JButton closeButton;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel10;
    private javax.swing.JPanel jPanel11;
    private javax.swing.JPanel jPanel12;
    private javax.swing.JPanel jPanel13;
    private javax.swing.JPanel jPanel14;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel37;
    private javax.swing.JPanel jPanel38;
    private javax.swing.JPanel jPanel39;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel40;
    private javax.swing.JPanel jPanel41;
    private javax.swing.JPanel jPanel42;
    private javax.swing.JPanel jPanel43;
    private javax.swing.JPanel jPanel44;
    private javax.swing.JPanel jPanel45;
    private javax.swing.JPanel jPanel46;
    private javax.swing.JPanel jPanel47;
    private javax.swing.JPanel jPanel48;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel52;
    private javax.swing.JPanel jPanel53;
    private javax.swing.JPanel jPanel54;
    private javax.swing.JPanel jPanel55;
    private javax.swing.JPanel jPanel56;
    private javax.swing.JPanel jPanel57;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JPanel jPanel64;
    private javax.swing.JPanel jPanel65;
    private javax.swing.JPanel jPanel66;
    private javax.swing.JPanel jPanel67;
    private javax.swing.JPanel jPanel68;
    private javax.swing.JPanel jPanel69;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JPanel jPanel70;
    private javax.swing.JPanel jPanel71;
    private javax.swing.JPanel jPanel72;
    private javax.swing.JPanel jPanel8;
    private javax.swing.JPanel jPanel9;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane10;
    private javax.swing.JScrollPane jScrollPane11;
    private javax.swing.JScrollPane jScrollPane12;
    private javax.swing.JScrollPane jScrollPane13;
    private javax.swing.JScrollPane jScrollPane14;
    private javax.swing.JScrollPane jScrollPane15;
    private javax.swing.JScrollPane jScrollPane18;
    private javax.swing.JScrollPane jScrollPane19;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane20;
    private javax.swing.JScrollPane jScrollPane21;
    private javax.swing.JScrollPane jScrollPane26;
    private javax.swing.JScrollPane jScrollPane27;
    private javax.swing.JScrollPane jScrollPane28;
    private javax.swing.JScrollPane jScrollPane29;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane30;
    private javax.swing.JScrollPane jScrollPane31;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JScrollPane jScrollPane5;
    private javax.swing.JScrollPane jScrollPane8;
    private javax.swing.JScrollPane jScrollPane9;
    private javax.swing.JTextArea jTextArea1;
    private javax.swing.JButton nextButton;
    private javax.swing.JButton previousButton;
    private javax.swing.JMenuItem step3HelpPT1;
    private javax.swing.JTextArea step3Ref1Q1NotesTA;
    private javax.swing.JTextArea step3Ref1Q1TA;
    private javax.swing.JTabbedPane step3Ref1Q1TP;
    private javax.swing.JRadioButton step3Ref1Q1rbNA;
    private javax.swing.JRadioButton step3Ref1Q1rbNo;
    private javax.swing.JRadioButton step3Ref1Q1rbObs;
    private javax.swing.JRadioButton step3Ref1Q1rbYes;
    private javax.swing.JTabbedPane step3Ref1Q2TP;
    private javax.swing.JTabbedPane step3Ref1Q3TP;
    private javax.swing.JTabbedPane step3Ref1Q4TP;
    private javax.swing.JTabbedPane step3Ref1Q5TP;
    private javax.swing.JTabbedPane step3Ref1Q6TP;
    private javax.swing.JTabbedPane step3Ref1tp;
    private javax.swing.JTextArea step3Ref2Q1NotesTA;
    private javax.swing.JTextArea step3Ref2Q1TA;
    private javax.swing.JRadioButton step3Ref2Q1rbNA;
    private javax.swing.JRadioButton step3Ref2Q1rbNo;
    private javax.swing.JRadioButton step3Ref2Q1rbObs;
    private javax.swing.JRadioButton step3Ref2Q1rbYes;
    private javax.swing.JTextArea step3Ref3Q1NotesTA;
    private javax.swing.JTextArea step3Ref3Q1TA;
    private javax.swing.JRadioButton step3Ref3Q1rbNA;
    private javax.swing.JRadioButton step3Ref3Q1rbNo;
    private javax.swing.JRadioButton step3Ref3Q1rbObs;
    private javax.swing.JRadioButton step3Ref3Q1rbYes;
    private javax.swing.JTextArea step3Ref4Q1NotesTA;
    private javax.swing.JTextArea step3Ref4Q1TA;
    private javax.swing.JRadioButton step3Ref4Q1rbNA;
    private javax.swing.JRadioButton step3Ref4Q1rbNo;
    private javax.swing.JRadioButton step3Ref4Q1rbObs;
    private javax.swing.JRadioButton step3Ref4Q1rbYes;
    private javax.swing.JTextArea step3Ref5Q1NotesTA;
    private javax.swing.JTextArea step3Ref5Q1TA;
    private javax.swing.JRadioButton step3Ref5Q1rbNA;
    private javax.swing.JRadioButton step3Ref5Q1rbNo;
    private javax.swing.JRadioButton step3Ref5Q1rbObs;
    private javax.swing.JRadioButton step3Ref5Q1rbYes;
    private javax.swing.JTextArea step3Ref5Q2NotesTA;
    private javax.swing.JTextArea step3Ref5Q2TA;
    private javax.swing.JRadioButton step3Ref5Q2rbNA;
    private javax.swing.JRadioButton step3Ref5Q2rbNo;
    private javax.swing.JRadioButton step3Ref5Q2rbObs;
    private javax.swing.JRadioButton step3Ref5Q2rbYes;
    private javax.swing.JTextArea step3Ref5Q3NotesTA;
    private javax.swing.JTextArea step3Ref5Q3TA;
    private javax.swing.JRadioButton step3Ref5Q3rbNA;
    private javax.swing.JRadioButton step3Ref5Q3rbNo;
    private javax.swing.JRadioButton step3Ref5Q3rbObs;
    private javax.swing.JRadioButton step3Ref5Q3rbYes;
    private javax.swing.JTextArea step3Ref6Q1NotesTA;
    private javax.swing.JTextArea step3Ref6Q1TA;
    private javax.swing.JRadioButton step3Ref6Q1rbNA;
    private javax.swing.JRadioButton step3Ref6Q1rbNo;
    private javax.swing.JRadioButton step3Ref6Q1rbObs;
    private javax.swing.JRadioButton step3Ref6Q1rbYes;
    private javax.swing.JTextArea step3Ref6Q2NotesTA;
    private javax.swing.JTextArea step3Ref6Q2TA;
    private javax.swing.JRadioButton step3Ref6Q2rbNA;
    private javax.swing.JRadioButton step3Ref6Q2rbNo;
    private javax.swing.JRadioButton step3Ref6Q2rbObs;
    private javax.swing.JRadioButton step3Ref6Q2rbYes;
    private javax.swing.JTextArea step3Ref6Q3NotesTA;
    private javax.swing.JTextArea step3Ref6Q3TA;
    private javax.swing.JRadioButton step3Ref6Q3rbNA;
    private javax.swing.JRadioButton step3Ref6Q3rbNo;
    private javax.swing.JRadioButton step3Ref6Q3rbObs;
    private javax.swing.JRadioButton step3Ref6Q3rbYes;
    private javax.swing.JTextArea step3Ref6Q4NotesTA;
    private javax.swing.JTextArea step3Ref6Q4TA;
    private javax.swing.JRadioButton step3Ref6Q4rbNA;
    private javax.swing.JRadioButton step3Ref6Q4rbNo;
    private javax.swing.JRadioButton step3Ref6Q4rbObs;
    private javax.swing.JRadioButton step3Ref6Q4rbYes;
    // End of variables declaration//GEN-END:variables
}
